import tkinter as tk
from tkinter import simpledialog


def createWebPartCodeBehind(title):
    f= open("../" + title + ".ascx.cs","w+")
    f.write("using System;\n")
    f.write("using System.Data;\n")
    f.write("using System.Collections;\n")
    f.write("using System.Web;\n")
    f.write("using System.Web.UI;\n")
    f.write("using System.Web.UI.WebControls;\n")
    f.write("\n")
    f.write("using CMS.PortalEngine.Web.UI;\n")
    f.write("using CMS.Helpers;\n")
    f.write("\n")
    f.write("public partial class CMSWebParts_AFSI_" + title + " : CMSAbstractWebPart\n")
    f.write("{\n")
    f.write("    #region \"Properties\"\n")
    f.write("    TestFile that is hopefully properly formatted\n")
    f.write("    #endregion\n")
    f.write("\n")
    f.write("    #region \"Methods\"\n")
    f.write("\n")
    f.write("    /// <summary>\n")
    f.write("    /// Content loaded event handler.\n")
    f.write("    /// </summary>\n")
    f.write("    public override void OnContentLoaded()\n")
    f.write("    {\n")
    f.write("        base.OnContentLoaded();\n")
    f.write("        SetupControl();\n")
    f.write("    }\n")
    f.write("\n")
    f.write("    /// <summary>\n")
    f.write("    /// Initializes the control properties.\n")
    f.write("    /// </summary>\n")
    f.write("    protected void SetupControl()\n")
    f.write("    {\n")
    f.write("        if (this.StopProcessing)\n")
    f.write("        {\n")
    f.write("            // Do not process\n")
    f.write("        }\n")
    f.write("        else\n")
    f.write("        {\n")
    f.write("            plcWrapper.DataBind();\n")
    f.write("        }\n")
    f.write("    }\n")
    f.write("\n")
    f.write("    /// <summary>\n")
    f.write("    /// Reloads the control data.\n")
    f.write("    /// </summary>\n")
    f.write("    public override void ReloadData()\n")
    f.write("    {\n")
    f.write("        base.ReloadData();\n")
    f.write("\n")
    f.write("        SetupControl();\n")
    f.write("    }\n")
    f.write("\n")
    f.write("    #endregion\n")
    f.write("}\n")
    f.close()

application_window = tk.Tk()
def textInput(text, prompt):
    return simpledialog.askstring(text, prompt, parent=application_window)


text = textInput("Title", "Please enter title:")
createWebPartCodeBehind(text)